# Use Node 18
FROM node:18

# Set working directory
WORKDIR /app

# Install Medusa CLI globally (optional but useful for running commands like `medusa migrations`)
RUN npm install -g @medusajs/medusa-cli

# Copy package.json and package-lock.json
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose Medusa's default port
EXPOSE 9000

# Start Medusa server
CMD ["npm", "run", "start"]
